### ISSUE TITLE
write tests for crawler.go

### ISSUE THREAD

**Issue by titaniumbones** [datatogether/sentry#38]
tests should cover all functions with CapitalizedNames and demonstrate an understanding of what the function is supposed to accomplish!

See [the Golang Book](https://www.golang-book.com/books/intro/12) for more information about testing in go.

This issue is part of #19, the testing coverage metaissue.

**Comment by chinchila** [comment]
Hello, can i go for this one?

**Comment by b5** [comment]
@chinchila Absolutely! We'd welcome any testing you can add here. If you need help on where to start feel free to ask & I'll try to point you in the right direction, otherwise, pull requests welcome!

**Comment by RvanBaarle** [comment]
I might be missing something, but I don't see any functions with CapitalizedNames in crawler.go

**Comment by chinchila** [comment]
@ActuallyRuben This means that the functions for testing should have capitalized names, for example for the function `urlIsWhitelisted`, the test function should follow `TestUrlIsWhitelisted`, i believe.

Is it ok to change `server_test.go` a little bit, i'm going to add a setup and shutdown function for the testing ( to populate the database with test data, to remove the test data from the database, load config file, etc )?

Do I need to create test for the function `memStats()`? I don't see much need because it is not based on sentry code, i mean it gets info from `runtime` and `fetchbot` libs.

**Comment by shapironick** [comment]
Hi @chinchila are you looking for feedback from @b5 on the above Q? ^^

**Comment by b5** [comment]
Ah sorry I missed this! @ActuallyRuben is right, none of these methods are Exported (no capital names).

@ActuallyRuben The single biggest thing we'd really appreciate for testing is setting up an "obstacle course" of static web pages that we can serve up with the `net/http/httptest` package to see if the crawler identifies the expected resources. This set of test pages should have both easy and difficult to identify links to write tests for the crawler against. If we had this set of pages in place, we could then work as a team to write tests thats run sentry through the course. Interested?

@chinchila, it's absolutely fine to modify code to do testing setup & teardown. In fact, we have a related project that does exactly this: https://github.com/datatogether/api/blob/master/main_test.go

If you have any interest in submitting a PR that brings the above patterns for DB setup & teardown in, I'd be grateful!

Thanks to you both :)

**Comment by chinchila** [comment]
Hi, i did some work, a simple webpage with some examples for the crawler.
I don't feel very comfortable with the 1 second wait to start the test, so i would like some help with a better solution. The test is failing because an url can't be crawled right. Inside `static/index.html` you can see that i've used a notation for same protocol links.

I didn't include any test with the javascripts loaded because i don't exactly know if sentry should crawl those.

**Comment by shapironick** [comment]
@chinchila, Are you looking for help from @b5? Please at him, so he doesn't miss it. Thanks!

**Comment by chinchila** [comment]
Thank you for the info, he already saw my PR. Sorry for this, i'm still new with open-source colab.

**Comment by bookmoons** [comment]
Thought I might try this one, but it looks like the pull request was merged. Is this issue still open?

**Comment by b5** [comment]
Oh I'm sorry, this is indeed fixed! closing. @bookmoons if you're interested feel free to comment on this (closed) issue with bits you'd be interested in learning with / working on & I'll try to help you find a good spot to get going. Any PR we get will receive feedback & hopefully we can all collaborate towards better code & better practices 😄.
